// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:176923857945:web:1c9eb0d6ef8655740b0688',
    messagingSenderId: '176923857945',
    projectId: 'evaluaciones-app-8dc23',
    authDomain: 'evaluaciones-app-8dc23.firebaseapp.com',
    storageBucket: 'evaluaciones-app-8dc23.firebasestorage.app',
    measurementId: 'G-FDF7BX9D0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:176923857945:android:6d799aa7a1e387a20b0688',
    messagingSenderId: '176923857945',
    projectId: 'evaluaciones-app-8dc23',
    storageBucket: 'evaluaciones-app-8dc23.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWPhbLHBEpvJXUWKirU2zOUOY8T1m61cA',
    appId: '1:176923857945:ios:b913e5eeed5f84b70b0688',
    messagingSenderId: '176923857945',
    projectId: 'evaluaciones-app-8dc23',
    storageBucket: 'evaluaciones-app-8dc23.firebasestorage.app',
    iosBundleId: 'com.example.evaluacionesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkqr5E1ylZe7tZV1mrokfuS6YcsdDJTcA',
    appId: '1:176923857945:web:f0796a63013124880b0688',
    messagingSenderId: '176923857945',
    projectId: 'evaluaciones-app-8dc23',
    authDomain: 'evaluaciones-app-8dc23.firebaseapp.com',
    storageBucket: 'evaluaciones-app-8dc23.firebasestorage.app',
    measurementId: 'G-L29MG4THEC',
  );

}